name: Test authentication in TF submit action

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: [self-hosted, self-hosted-linux-amd64-jammy-private-endpoint-medium]

    steps:
      - uses: actions/checkout@v4

      - name: Submit job
        id: tf-submit
        uses: k-s-0/testflinger/.github/actions/submit@main
        with:
          job-path: ".github/test_job.yaml"
          poll: true
          client-id: "${{ secrets.CLIENT_ID }}"
          secret-key: "${{ secrets.SECRET_KEY }}"
